---
title: "analyse_laktat_seasons"
author: "ari"
date: "1 6 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)

library(readxl)

library(GGally)

source("functions/aggregate_seasons.R")
```

get the laktat data:
- dates and calculated values
- aggregate history of the 8 weeks before


### read Laktat test data
```{r}

path_laktat <- "C:/Users/rigle/Documents/Training/Laktat FTP/"

laktat_data <- read_excel(str_c(path_laktat,"Laktat.xls"))

laktat_data <- laktat_data %>% rename(watt = Watt,
                        laktat = Laktat,
                        date = Datum,
                        person = Person,
                        intervall_dauer = Intervalllänge)


laktat_data <- laktat_data %>% mutate(year =year(date),
                           month=month(date))


lactat_calculated  <-read_csv2(str_c(path_laktat,"laktat_watt.csv")) %>% rename("date" = "datum")
```



### Read export data from Goldencheetah

```{r}
data_gc <-  read_csv( "Results/goldencheetah_tss.csv") %>% 
                  mutate(date = parse_character(Datum, locale = locale(encoding = "latin1")),                                                      date = as.Date(date,format = "%d.%B %Y")) %>% 
                  select( date, everything(), -Datum, -dauer) %>% 
                rename("hr" = "hf_mean",
                       "duration" = "zeit_in_bewegung") %>%
                    filter(duration >0)                                                                                        
data_gc <- data_gc %>% mutate(hr_watt = case_when((w_mean >0) & (hr >0) ~ hr/w_mean))
                                                                                            
data_gc %>% arrange(desc(date))

```

```{r}
data_gc %>% group_by(year(date)) %>% count() 
```




```{r}
data_gc %>% ggplot(aes(x=date))+
  geom_point(aes(y = hr_watt) )+
  geom_smooth((aes(y=hr_watt)))+
  coord_cartesian(ylim = c(0,2))
```

```{r}
data_gc %>% ggplot(aes(x=date))+
  geom_point(aes(y = duration) )+
  geom_smooth((aes(y=duration)))
```

```{r}
data_gc %>% mutate(week = week(date),
                   year = year(date)) %>%
  group_by(year,week) %>% 
  summarise(TSS =sum(TSS,na.rm = TRUE),
            date =min(date)) %>%
ggplot(aes(x=date))+
  geom_point(aes(y = TSS) )+
  geom_smooth((aes(y=TSS)))+
  labs(y = "TSS/ week")+
  theme_light()
```

```{r}
data_gc %>% mutate(week = week(date),
                   year = year(date)) %>%
  group_by(year,week) %>% 
  summarise(duration =sum(duration,na.rm = TRUE),
            TSS =sum(TSS,na.rm = TRUE),
            date =min(date)) %>%
  mutate(TSS_duration = TSS/duration) %>%
ggplot(aes(x=date))+
  geom_point(aes(y = TSS_duration) )+
  geom_smooth((aes(y=TSS_duration)))+
  labs(y = "TSS/ duration / week")+
  theme_light()
```

```{r}
data_gc %>% mutate(week = week(date),
                   year = year(date)) %>%
  group_by(year,week) %>% 
  summarise(watt =mean(w_mean,na.rm = TRUE),
            hr =mean(hr,na.rm = TRUE),
            date =min(date)) %>%
  mutate(hr_watt = hr/watt) %>%
  
  filter(hr_watt < 1.5) %>%
  
ggplot(aes(x=date))+
  geom_point(aes(y = hr_watt) )+
  geom_smooth((aes(y=hr_watt)))+
  geom_hline(yintercept = 0.8)+
  #coord_cartesian(ylim = c(0,3))+
  labs(y = "hr/ watt / week")+
  theme_light()
```

### Calculate the season dates

```{r}
duration_weeks = 8

today_date = tibble(date = today())
hour_of_power = tibble(date = as.Date(c("2017-05-22", "2017-03-24", "2016-07-20")),
                       w_5mmol = c(286, 282, 261))

laktat_test_dates <- laktat_data %>% distinct(date) %>% bind_rows(today_date) %>% mutate(date_start = date - weeks(duration_weeks))

lactat_calculated <- lactat_calculated  %>% bind_rows(today_date) %>% 
                                            bind_rows(hour_of_power) %>%mutate(date_start = date - weeks(duration_weeks))

lactat_calculated %>% arrange(desc(date))
```

### Summarise the metrics for each season

```{r}
activites_aggregated_list <- list()
for (i in seq_along(lactat_calculated$date)) {
  date_start = lactat_calculated$date_start[i]
  date_end = lactat_calculated$date[i]
  
  w_2mmol <- lactat_calculated$w_2mmol[i]
  w_5mmol <- lactat_calculated$w_5mmol[i]
  
  dates = tibble(date = seq(ymd(date_start), ymd(date_end), by = "1 day"))
  
  activities_data <- dates %>% left_join(data_gc)  
  
  activites_aggregated_list[[i]] <- activities_data %>% mutate(long = case_when(duration >= 3 ~ 1, TRUE ~ 0),
                                                               high_TSS = case_when(TSS > 100 ~1, TRUE ~ 0)) %>%
    
                                                summarise(n = n(),
                                                          n_long = sum(long, na.rm = TRUE),
                                                          n_high_TSS = sum(high_TSS, na.rm = TRUE),
                                                          TSS = sum(TSS, na.rm = TRUE),
                                                       duration = sum(duration, na.rm = TRUE),
                                                       watt = mean(w_mean, na.rm = TRUE)) %>%
                              mutate(date_test = date_end,
                                     w_2mmol = w_2mmol,
                                     w_5mmol = w_5mmol)
  
}

activites_aggregated <- activites_aggregated_list %>% bind_rows()

activites_aggregated %>%
  ggplot(aes(x=date_test))+
  geom_line(aes(y = duration, color = "duration"))+
  geom_line(aes(y = w_2mmol, color = "2mmol"))+
  geom_line(aes(y = w_5mmol, color = "5mmol"))+
  geom_line(aes(y = TSS/10, color = "TSS"))+
  geom_point(aes(y = TSS/10, color = "TSS"))+
  geom_point(aes(y=n_high_TSS, color = "n_high_TSS"))+
  #geom_line(aes(y = hr, color = "hr"))+
  geom_line(aes(y = watt, color = "watt"))

activites_aggregated %>% #mutate_at(c("duration", "w_2mmol", "w_5mmol", "TSS", "watt", "n_long", "n_high_TSS"), scale) %>%
  pivot_longer(cols = c(duration, w_2mmol, w_5mmol, TSS, watt, n_long,n_high_TSS)) %>%
  ggplot(aes(x=date_test))+
  geom_line(aes(y=value))+
  geom_point(aes(y=value))+
  facet_wrap(name~., ncol = 1, scales = "free_y")+
  theme_light()

```

```{r}

v_lines <- tibble(x = c(today(), "2021-01-28", "2020-07-07", "2017-05-22"))
h_lines <- tibble(y = c(200,250))

p_laktat <- activites_aggregated %>%
  ggplot(aes(x=date_test))+
  geom_line(aes(y = w_2mmol, color = "2 mmol"))+
  geom_point(aes(y = w_2mmol, color = "2 mmol"))+
  geom_line(aes(y = w_5mmol, color = "5 mmol"))+
  geom_point(aes(y = w_5mmol, color = "5 mmol"))+
  geom_vline(xintercept = v_lines$x)+
  geom_hline(yintercept = h_lines$y)+
  labs(x= "test date",
       y= "Watt",
       color = "Laktat:")+
  theme_light()


p_duration <- activites_aggregated %>%
  ggplot(aes(x=date_test))+
  #geom_line(aes(y = TSS, color = "TSS"))+
  #geom_point(aes(y = TSS, color = "TSS"))+
  geom_line(aes(y = duration, color = "duration"))+
  geom_point(aes(y = duration, color = "duration"))+
  geom_vline(xintercept = v_lines$x)+
  labs(x= "test date",
       y= "duration")+
  theme_light()

p_TSS <- activites_aggregated %>%
  ggplot(aes(x=date_test))+
  geom_line(aes(y = TSS, color = "TSS"))+
  geom_point(aes(y = TSS, color = "TSS"))+
  geom_vline(xintercept = v_lines$x)+
  labs(x= "test date",
       y= "TSS")+
  theme_light()

library(patchwork)
p_laktat / p_duration / p_TSS

```

```{r}

activities_all <- activites_aggregated %>% distinct(date_test, .keep_all = TRUE) %>%
  mutate(year = lubridate::year(date_test) %>% as.factor())
activities_today <- activities_all %>% filter(date_test == today_date$date)

activities_all %>% 
  ggplot(aes(y=w_2mmol))+
  geom_jitter(aes(x=duration, color =year))+
  geom_vline(xintercept = activities_today$duration)
```

```{r}

activities_all %>% 
  ggplot(aes(y=w_2mmol))+
  geom_jitter(aes(x=TSS, color = year))+
  geom_vline(xintercept = activities_today$TSS)+
  geom_line(aes(x=TSS, group = year, color = year))
```
```{r}

activities_all %>% 
  ggplot(aes(y=w_5mmol))+
  geom_jitter(aes(x=duration, color = year))+
  geom_line(aes(x=duration, group = year, color = year))
```


```{r}

activities_all %>% mutate(w_5mmol = round(w_5mmol /10) %>% as.factor())%>%
  ggplot(aes(y=duration))+
  geom_jitter(aes(x=TSS, color = w_5mmol))+
  geom_vline(xintercept = activities_today$TSS)
```

```{r}

activities_all %>% 
  ggplot(aes(y=duration))+
  geom_jitter(aes(x=TSS, color = year))+
  geom_point(data= activities_today, aes(x=TSS, color = "today"),size = 3)
```

## Funkfunctions/aggregate_seasons.Rion Wochen Aggregation

```{r}
duration_weeks = 12



today_date = tibble(date = today())
hour_of_power = tibble(date = as.Date(c("2017-05-22", "2017-03-24", "2016-07-20")),
                       w_5mmol = c(286, 282, 261))


generate_season_summary <- function(lactat_data, data_gc, duration_weeks){

  today_date = tibble(date = today())
  
  lactat_calculated <- lactat_data  %>% bind_rows(today_date) %>% 
                                              mutate(date_start = date - weeks(duration_weeks)) 
  
  activites_aggregated_list <- list()
for (i in seq_along(lactat_calculated$date)) {
    date_start = lactat_calculated$date_start[i]
    date_end = lactat_calculated$date[i]
    
    w_2mmol <- lactat_calculated$w_2mmol[i]
    w_5mmol <- lactat_calculated$w_5mmol[i]
    
    dates = tibble(date = seq(ymd(date_start), ymd(date_end), by = "1 day"))
    
    activities_data <- dates %>% left_join(data_gc)  
    
    activites_aggregated_list[[i]] <- activities_data %>% 
                                          mutate(long = case_when(duration >= 3 ~ 1, TRUE ~ 0),
                                                 high_TSS = case_when(TSS > 100 ~1, TRUE ~ 0)) %>%
      
                                                  summarise(n = n(),
                                                            n_long = sum(long, na.rm = TRUE),
                                                            n_high_TSS = sum(high_TSS, na.rm = TRUE),
                                                            TSS = sum(TSS, na.rm = TRUE),
                                                         duration = sum(duration, na.rm = TRUE),
                                                         watt = mean(w_mean, na.rm = TRUE)) %>%
                                mutate(date_test = date_end,
                                       w_2mmol = w_2mmol,
                                       w_5mmol = w_5mmol)
    
  }
  
  result= bind_rows(activites_aggregated_list) %>% 
                        distinct(date_test, .keep_all = TRUE) %>%
                        mutate(year = lubridate::year(date_test) %>% as.factor())
  return(result)
}

```

```{r}
plot_w_duration <- function(plot_data, duration_weeks){
  
plt_duration <- plot_data %>% 
        ggplot(aes(y=w_2mmol))+
        geom_jitter(aes(x=duration, color = year))+
        #geom_vline(xintercept = activities_today$TSS)+
        geom_line(aes(x=duration, group = year, color = year))+
  labs(title = str_c("duration last ", duration_weeks, " weeks"))+
  theme_light()

plt_tss <- plot_data %>% 
        ggplot(aes(y=w_2mmol))+
        geom_jitter(aes(x=TSS, color = year))+
        #geom_vline(xintercept = activities_today$TSS)+
        geom_line(aes(x=TSS, group = year, color = year))+
  geom_smooth(aes(x=TSS))+
  labs(title = str_c("TSS last ", duration_weeks, " weeks"))+
  theme_light()

p_result = plt_duration / plt_tss
return(p_result)
  
}

calc_and_plot <-function(lactat_data, data_gc, duration_weeks){
  
  plot_data <- generate_season_summary(lactat_data, data_gc,duration_weeks)
  plot_w_duration(plot_data,duration_weeks)
}

```


```{r message=FALSE, warning=FALSE}
lactat_calculated <- lactat_calculated  %>% bind_rows(hour_of_power)  %>% distinct(date_start, .keep_all = TRUE)

duration_weeks =12 
calc_and_plot(lactat_calculated, data_gc, 12)
```

```{r}
calc_and_plot(lactat_calculated, data_gc, 10)
```


```{r}
calc_and_plot(lactat_calculated, data_gc, 11)
```

```{r}
activites_aggregated_list <- list()
for (i in seq_along(lactat_calculated$date)) {
  date_start = lactat_calculated$date_start[i]
  date_end = lactat_calculated$date[i]
  
  w_2mmol <- lactat_calculated$w_2mmol[i]
  w_5mmol <- lactat_calculated$w_5mmol[i]
  
  dates = tibble(date = seq(ymd(date_start), ymd(date_end), by = "1 day"))
  
  activities_data <- dates %>% left_join(data_gc)  
  
  activites_aggregated_list[[i]] <- activities_data %>% mutate(long = case_when(duration >= 3 ~ 1, TRUE ~ 0),
                                                               high_TSS = case_when(TSS > 100 ~1, TRUE ~ 0)) %>%
    
                                                summarise(n = n(),
                                                          n_long = sum(long, na.rm = TRUE),
                                                          n_high_TSS = sum(high_TSS, na.rm = TRUE),
                                                          TSS = sum(TSS, na.rm = TRUE),
                                                       duration = sum(duration, na.rm = TRUE),
                                                       watt = mean(w_mean, na.rm = TRUE)) %>%
                              mutate(date_test = date_end,
                                     w_2mmol = w_2mmol,
                                     w_5mmol = w_5mmol)
  
}

activites_aggregated <- activites_aggregated_list %>% bind_rows()

```

### Correlation

```{r}
library(GGally)

data_10_weeks <- generate_season_summary(lactat_calculated, data_gc, 10)


data_10_weeks %>% select(w_2mmol, w_5mmol, everything(),-n, - date_test, -year) %>% ggcorr(label = TRUE)
```

```{r}
data_12_weeks <- generate_season_summary(lactat_calculated, data_gc, 12)


data_12_weeks %>% select(w_2mmol, w_5mmol, everything(),-n, - date_test, -year) %>% ggcorr(label = TRUE)
```

## model


#####   ALTES ----------------------------------

```{r}
files <- tibble(files = list.files("Results/")) %>% filter(str_detect(files,"ml_data_2")) %>% 
                mutate(files = str_c("Results/",files)) %>% pull()
files


aggregate_raw_data <- function(data){
  data_aggregated <- data %>% group_by(date,device, workout_code, start_time) %>%
                                
                                    summarise(duration_sec = max(sec),
                                               watt = mean(watt),
                                              hr = mean(hr))
  
  return(data_aggregated)
}



data_aggregated_list <- list()
for (i in seq_along(files)) {
    data_raw<- read_rds(files[i])
    data_aggregated_list[[i]] <- data_raw %>% aggregate_raw_data()
    
  
}

data_aggregated <- bind_rows(data_aggregated_list)

data_aggregated
```


```{r}
activites_aggregated_list <- list()
for (i in seq_along(lactat_calculated$date)) {
  date_start = lactat_calculated$date_start[i]
  date_end = lactat_calculated$date[i]
  
  w_2mmol <- lactat_calculated$w_2mmol[i]
  w_5mmol <- lactat_calculated$w_5mmol[i]
  
  dates = tibble(date = seq(ymd(date_start), ymd(date_end), by = "1 day"))
  
  activities_data <- dates %>% left_join(data_aggregated) %>% filter(!is.na(workout_code))  
  
  activites_aggregated_list[[i]] <- activities_data %>% summarise(n = n(),
                                                       hr_time = sum(hr*duration_sec),
                                                       watt_time = sum(watt*duration_sec),
                                                       duration_sec_sum = sum(duration_sec)) %>%
                              mutate(duration = round(duration_sec_sum/3600,1),
                                     watt = watt_time / duration_sec_sum,
                                     hr = hr_time / duration_sec_sum,
                                     date_test = date_end,
                                     w_2mmol = w_2mmol,
                                     w_5mmol = w_5mmol)
  
}

activites_aggregated <- activites_aggregated_list %>% bind_rows()

activites_aggregated %>%
  ggplot(aes(x=date_test))+
  geom_line(aes(y = duration, color = "duration"))+
  geom_line(aes(y = w_2mmol, color = "2mmol"))+
  geom_line(aes(y = w_5mmol, color = "5mmol"))+
  geom_line(aes(y = hr, color = "hr"))+
  geom_line(aes(y = watt, color = "watt"))
```

```{r message=FALSE, warning=FALSE}

activites_aggregated %>%select(duration, w_2mmol, w_5mmol,watt, hr) %>% ggpairs()

```

```{r}
activites_aggregated %>%select(date_test, duration, w_2mmol, w_5mmol,n) %>% 
      filter(w_2mmol > 190 & duration <20)
```


### read trainings data
```{r}
data_2016_raw<- read_rds( "Results/test_ml_data_2016.rds")

data_2017_raw<- read_rds( "Results/test_ml_data_2017.rds")

data_2018_raw<- read_rds( "Results/test_ml_data_2018.rds")

data_2019_raw<- read_rds( "Results/test_ml_data_2019.rds")

data_2020_raw<- read_rds( "Results/test_ml_data_2020.rds")

data_2021_raw<- read_rds( "Results/test_ml_data_2021.rds")

data_2021_raw %>% summarise(max(date))
```

